const express = require('express')
const cors = require('cors')
const app = express()
const port = process.env.PORT || 5000;
const dbconfig = require('./dbconfig')
app.use(cors())
app.use(express.json())
const usersRoute = require('./routes/usersRoute')
const invRoute = require('./routes/invRoute')
const dashboardRoute = require('./routes/dashboardRoute')
app.use('/api/users', usersRoute)
app.use('/api/inventory', invRoute)
app.use('/api/dashboard', dashboardRoute)

app.listen(port, ()=>console.log(`Server started at ${port}`))